### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [ViriAldi/HomeworkCycle2020#1]
"Визначення найкоротшого шляху між 2-ма точками земної поверхні" по дорогах чи обчислюється якось прохідність маршруту?
Тема: Пошук та візуалізація шляху з врахуванням ландшафту.

**Comment by ViriAldi** [comment]
Обчислюється прохідність маршруту (приблизно створюється граф точок ландшафту (сітка) зі зваженими ребрами і обчислюється найкоротший шлях в графі, вага ребра - відстань між точками (з урахуванням трьох координат)). Ще можна не брати до шляху точки, що знаходяться на похилій поверхні (коли в одному з напрямів великий кут), або регулювати максимальний кут нахилу шляху (це за бажанням користувача, залежно від його вимог). Використання баз даних чи API для доріг ітд поки що не планується, хоча є ще ідеї реалізації розширення подібної функціональності.
